dethatcher_la_control:
  ros__parameters:
    serial_port: "/dev/ttyACM2"  # Example serial port for Arduino
    baud_rate: 9600

dethatcher_motor_control:
  ros__parameters:
    serial_port: "/dev/ttyACM2"  # Example serial port for Arduino
    baud_rate: 9600

dethatcher_ultra_sensor:
  ros__parameters:
    sensor_param_1: "value1"
    sensor_param_2: "value2"

dethatcher_planner:
  ros__parameters:
    planner_param_1: "value1"
    planner_param_2: "value2"
