weed_control_la_control:
  ros__parameters:
    serial_port: "/dev/ttyACM1"  # Example serial port for Arduino
    baud_rate: 9600
    max_speed_percentage: 20

weed_control_stepper_control:
  ros__parameters:
    stepper_param_1: "value1"
    stepper_param_2: "value2"

weed_control_ultra_sensor:
  ros__parameters:
    sensor_param_1: "value1"
    sensor_param_2: "value2"

weed_control_planner:
  ros__parameters:
    planner_param_1: "value1"
    planner_param_2: "value2"

weed_control_cam:
  ros__parameters:
    cam_param_1: "value1"
    cam_param_2: "value2"
